markdown: kramdown
highlighter: rouge
permalink: pretty
gems:
  - jekyll-sitemap

permalink: /blog/:year/:month/:day/:title/
future: true

name: Jonas Fredriksson
baseurl: '/'
url: https://fredriksson.io

meta:
  description: Jonas Fredriksson is a Software Engineer / IT Architect / Developer living in Stockholm, Sweden
  keywords: Jonas Fredriksson, Stockholm, Software engineer, Developer, Software developer, Blog

author:
  name: Jonas Fredriksson
  twitter: https://twitter.com/jonasfr
  github: https://github.com/jonasf
  linkedin: https://www.linkedin.com/in/jonasfredriksson

facebook_app_id: 409330955916878

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      is_post: true