markdown: kramdown
highlighter: rouge
permalink: pretty
gems:
  - jekyll-sitemap

name: Jonas Fredriksson
tagline: Learn something new
baseurl: '/'
url: https://fredriksson.io

meta:
  description: Jonas Fredriksson is a software engineer / developer living in Stockholm, Sweden
  keywords: Jonas Fredriksson, Stockholm, Software engineer, Developer, Software developer, Blog

author:
  name: Jonas Fredriksson
  email: l.jonas.fredriksson@gmail.com
  twitter: https://twitter.com/jonasfr
  github: https://github.com/jonasf
  linkedin: https://www.linkedin.com/in/jonasfredriksson

facebook_app_id: 409330955916878

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      is_post: true